apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-quiz-staging
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    # Chemin unique pour les données de staging sur le nœud EKS
    path: /data/db-quiz-staging 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-quiz-staging
  namespace: quiz-staging
spec: 
  accessModes:  
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" 
