apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: quiz-staging
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # Le tag de l'image sera remplacé par la pipeline CI/CD
        image: 228578233417.dkr.ecr.us-east-1.amazonaws.com/quiz-app-repo:frontend-7a3d5151
        envFrom:
        - configMapRef:
            name: quiz-app-config
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: quiz-staging
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
  ports:
  - port: 8080 # Le service peut exposer un port différent
    targetPort: 80 # Mais il doit cibler le port 80 du conteneur Nginx
    protocol: TCP
  type: ClusterIP
