apiVersion: batch/v1
kind: Job
metadata:
  name: populate-db-job
  namespace: quiz-staging
spec:
  template:
    spec:
      containers:
      - name: populate-db
        # Le tag de l'image sera remplacé par la pipeline CI/CD
        image: 228578233417.dkr.ecr.us-east-1.amazonaws.com/populate-repo:populate-0b9f3255
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-uri
      restartPolicy: Never
  backoffLimit: 4
