# Fichier : populate-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: populate-db-job
  namespace: quiz-staging # ou 'quiz' pour la production
  # --- AJOUTEZ CE BLOC D'ANNOTATIONS ---
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  # ------------------------------------
spec:
  template:
    spec:
      containers:
      - name: populate-db
        # L'image sera mise à jour par la pipeline CI
        image: 228578233417.dkr.ecr.us-east-1.amazonaws.com/populate-repo:populate-8c9df7aa
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-uri
      restartPolicy: Never
  backoffLimit: 4
