version: '3.8'

# Fichier docker-compose final pour le test DAST avec Nginx.

services:
  # --- Service Nginx (Point d'entrée unique) ---
  nginx:
    image: nginx:latest
    container_name: quiz-nginx-proxy
    ports:
      - "80:80" # Seul port exposé à l'extérieur (vers le runner et ngrok).
    volumes:
      # Monte notre fichier de configuration personnalisé dans le conteneur.
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # Nginx ne démarrera que lorsque le backend et le frontend seront "sains".
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - quiz-net

  # --- Service Backend (API) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      mongo:
        condition: service_started
    networks:
      - quiz-net
    # Healthcheck : Vérifie si le service backend est prêt à recevoir des requêtes.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Service Frontend (Interface utilisateur ) ---
  frontend:
    build:
      context: ./quiz-app
      dockerfile: Dockerfile
    container_name: quiz-frontend
    environment:
      # L'URL de l'API est relative. Nginx s'occupera de la redirection.
      - VITE_REACT_APP_API_URL=/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - quiz-net
    # Healthcheck : Vérifie si le serveur de développement du frontend est prêt.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Service Base de données ---
  mongo:
    image: mongo:4.4.6
    container_name: quiz-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - quiz-net

  # --- Tâche d'initialisation de la base de données ---
  populate-db:
    build:
      context: ./backend
      dockerfile: Dockerfile.populate
    container_name: quiz-populate
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      mongo:
        condition: service_started
    networks:
      - quiz-net

# Réseau commun pour tous les services
networks:
  quiz-net:
    driver: bridge

# Volume pour la persistance des données MongoDB
volumes:
  mongo-data:
