# Fichier : /docker-compose.dast.yml
version: '3.8'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo_dast
    networks:
      - quiz-net

  backend:
    # Le tag sera injecté par le pipeline
    image: 228578233417.dkr.ecr.us-east-1.amazonaws.com/iovision-repo:BACKEND_IMAGE_TAG
    container_name: backend_dast
    networks:
      - quiz-net
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      - mongo

  frontend:
    # Cette image sera construite localement dans le pipeline
    image: local/frontend-dast:latest
    container_name: frontend_dast
    networks:
      - quiz-net
    ports:
      # Le port 80 de Nginx est mappé sur le port 8080 du runner
      - "8080:80"
    depends_on:
      - backend

  populate:
    # Le tag sera injecté par le pipeline
    image: 228578233417.dkr.ecr.us-east-1.amazonaws.com/populate-repo:POPULATE_IMAGE_TAG
    container_name: populate_dast
    networks:
      - quiz-net
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      - mongo

networks:
  quiz-net:
    driver: bridge
