version: '3.8'

services:
  backend:
    image: ${BACKEND_IMAGE_URI}
    container_name: dast-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    # --- CORRECTION --- : On expose le port du backend
    ports:
      - "3000:3000"
    depends_on:
      populate:
        condition: service_completed_successfully
    networks:
      - dast-network

  frontend:
    image: ${FRONTEND_IMAGE_URI}
    container_name: dast-frontend
    ports:
      - "8080:8080"
    environment:
      # --- CORRECTION --- : L'URL du backend pointe maintenant vers localhost
      # Le frontend (dans le navigateur) appellera le backend via le port exposé sur la machine hôte.
      - VITE_REACT_APP_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    networks:
      - dast-network

  mongo:
    image: mongo:4.4.6
    container_name: dast-mongo
    networks:
      - dast-network

  populate:
    image: ${POPULATE_IMAGE_URI}
    container_name: dast-populate
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    networks:
      - dast-network

networks:
  dast-network:
