# Fichier docker-compose final et nettoyé.
# La directive 'version' est obsolète et a été retirée.

services:
  # --- Service Nginx (Point d'entrée unique) ---
  nginx:
    image: nginx:latest
    container_name: quiz-nginx-proxy
    ports:
      - "80:80" # Seul port exposé à l'extérieur.
    volumes:
      # Monte notre fichier de configuration personnalisé dans le conteneur.
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # Attend simplement que les conteneurs backend et frontend soient démarrés.
      backend:
        condition: service_started
      frontend:
        condition: service_started
    networks:
      - quiz-net

  # --- Service Backend (API) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      mongo:
        condition: service_started
    networks:
      - quiz-net

  # --- Service Frontend (Interface utilisateur) ---
  frontend:
    build:
      context: ./quiz-app
      dockerfile: Dockerfile
    container_name: quiz-frontend
    environment:
      # Syntaxe correcte pour la variable d'environnement.
      # C'est cette valeur qui sera utilisée par le code React.
      VITE_REACT_APP_API_URL: /api
    depends_on:
      backend:
        condition: service_started
    networks:
      - quiz-net

  # --- Service Base de données ---
  mongo:
    image: mongo:4.4.6
    container_name: quiz-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - quiz-net

  # --- Tâche d'initialisation de la base de données ---
  populate-db:
    build:
      context: ./backend
      dockerfile: Dockerfile.populate
    container_name: quiz-populate
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      mongo:
        condition: service_started
    networks:
      - quiz-net

# Réseau commun pour tous les services
networks:
  quiz-net:
    driver: bridge

# Volume pour la persistance des données MongoDB
volumes:
  mongo-data:
