version: '3.8'

services:
  # --- NOUVEAU : Service Nginx Reverse Proxy ---
  nginx:
    image: nginx:latest
    container_name: quiz-nginx-proxy
    ports:
      - "80:80" # On expose le port 80 de Nginx sur la machine hôte. C'est ce port que ngrok va utiliser.
    volumes:
      # On monte notre fichier de configuration dans le conteneur Nginx.
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - quiz-net

  # --- Service Backend (inchangé) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      - mongo
    networks:
      - quiz-net
    # Pas besoin d'exposer de port ici, Nginx s'en charge.

  # --- Service Frontend (modifié) ---
  frontend:
    build:
      context: ./quiz-app
      dockerfile: Dockerfile
    container_name: quiz-frontend
    environment:
      # IMPORTANT : L'URL de l'API est maintenant relative, car Nginx gère la redirection.
      - VITE_REACT_APP_API_URL=/api
    depends_on:
      - backend
    networks:
      - quiz-net
    # Pas besoin d'exposer de port ici, Nginx s'en charge.

  # --- Services mongo et populate-db (inchangés) ---
  mongo:
    image: mongo:4.4.6
    container_name: quiz-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - quiz-net

  populate-db:
    build:
      context: ./backend
      dockerfile: Dockerfile.populate
    container_name: quiz-populate
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      - mongo
    networks:
      - quiz-net

networks:
  quiz-net:
    driver: bridge

volumes:
  mongo-data:
