# Fichier: docker-compose.dast.yml

services:
  proxy:
    image: nginx:1.25-alpine
    container_name: dast-proxy
    ports:
      - "8080:80"
    volumes:
      # Ce chemin est maintenant valide car l'étape 4 du workflow crée ce fichier
      - ./dast-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dast-network

  backend:
    image: ${BACKEND_IMAGE_URI}
    container_name: dast-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      populate:
        condition: service_completed_successfully
    networks:
      - dast-network

  frontend:
    image: ${FRONTEND_IMAGE_URI}
    container_name: dast-frontend
    environment:
      - VITE_REACT_APP_API_URL=/api
    depends_on:
      - backend
    networks:
      - dast-network

  mongo:
    image: mongo:4.4.6
    container_name: dast-mongo
    networks:
      - dast-network

  populate:
    image: ${POPULATE_IMAGE_URI}
    container_name: dast-populate
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    networks:
      - dast-network

networks:
  dast-network:
    driver: bridge
