apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/wissNasri/app.git'
    targetRevision: main
    path: kubernetes-manifest-staging
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: quiz-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
