apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-quiz
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 

  hostPath:
    # Chemin de stockage unique sur le disque du nœud EKS.
    path: /data/db-quiz 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-quiz
  namespace: quiz
spec: 
  accessModes:  
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Ligne cruciale qui force l'utilisation du PV manuel ci-dessus.
  storageClassName: "" 
