# 05-database.yaml (Version finale avec Init Container)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: quiz
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      
      # --- LA SOLUTION EST ICI ---
      initContainers:
      - name: set-volume-permissions
        image: busybox:1.36 # Une image linux minimale
        # On exécute cette commande en tant que root pour avoir les droits
        command: ["sh", "-c", "chown -R 999:999 /data/db"]
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      
      containers:
      - name: mongo
        image: mongo:4.4.6
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 15
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi" # On garde la version réduite qui a fonctionné
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc-quiz
---    
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: quiz
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
