# kubernetes-manifest/frontend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: quiz
  labels:
    app: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # L'image sera mise à jour par le pipeline
        image: 228578233417.dkr.ecr.us-east-1.amazonaws.com/quiz-app-repo:frontend-4ab44dfe
        envFrom:
        - configMapRef:
            name: quiz-app-config
        ports:
        # CORRECTION : Le conteneur écoute sur le port 80
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: quiz
spec:
  selector:
    app: frontend
  ports:
  # CORRECTION : Le service doit cibler le port 80 du conteneur
  - port: 8080 # Le service peut toujours exposer le port 8080...
    targetPort: 80 # ...mais il doit rediriger le trafic vers le port 80 du pod.
    protocol: TCP
  type: ClusterIP
