apiVersion: batch/v1
kind: Job
metadata:
  name: populate-db-job
  namespace: quiz
spec:
  template:
    spec:
    
      containers:
      - name: populator
        # L'image que nous venons de créer à l'étape 2
        image: 228578233417.dkr.ecr.us-east-1.amazonaws.com/iovision-repo:populate-1d8727b5
        env:
        # Le Job a besoin de savoir comment se connecter à Mongo, comme le backend
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-uri
      # Le Job ne doit pas redémarrer en cas d'échec, il doit juste s'arrêter.
      restartPolicy: Never
  # Le Job ne doit pas se relancer plus de 4 fois s'il échoue.
  backoffLimit: 4
