apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret-staging
  namespace: quiz-staging
type: Opaque
data:
  # Valeur encodée en Base64 pour "mongodb://mongo-service-staging.quiz-staging:27017/quizdb"
  mongo-uri: "bW9uZ29kYjovL21vbmdvLXNlcnZpY2Utc3RhZ2luZy5xdWl6LXN0YWdpbmc6MjcwMTcvcXVpemRi"
