name: Analyse de Sécurité MERN Frontend (minimal)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write   # <<<<< autorise l'upload SARIF vers GitHub Security

jobs:
  scan-frontend:
    name: Scan du Frontend avec Trivy
    runs-on: self-hosted
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t quiz-app-frontend:latest quiz-app

      - name: Trivy Image Scan (SARIF)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'quiz-app-frontend:latest'
          format: 'sarif'
          output: 'trivy-report.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif
