name: Analyse de Sécurité MERN Frontend (avec échec sur vulnérabilité critique)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-frontend:
    name: Analyse du Frontend (React.js)
    runs-on: self-hosted

    steps:
      # --------------------------------------------------
     
      # --------------------------------------------------
      - name: Run Checkov CLI
        run: |
          pip install checkov
          mkdir -p quiz-app/reports
          checkov -d ./kubernetes-manifest -o cli -o json -o-file quiz-app/reports/checkov-report.json || true


      # --------------------------------------------------
      # Upload des rapports
     
      - name: Upload Checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-frontend-report
          path: quiz-app/reports/checkov-report.json
          if-no-files-found: warn
