# Nom du workflow, très spécifique à sa seule tâche.
name: 1 - Gitleaks Secret Scan

on: [push]

jobs:
  gitleaks-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1 : Récupérer le code.
      - name: 1. Checkout Code
        uses: actions/checkout@v4
        # --- CORRECTION CRUCIALE ---
        # 'fetch-depth: 0' dit à l'action de cloner TOUT l'historique de la branche.
        # Sans cela, Gitleaks ne peut scanner que le dernier commit.
        with:
          fetch-depth: 0

      # Étape 2 : Exécuter Gitleaks.
      - name: 2. Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
