name: Analyse de Sécurité MERN Frontend (SARIF uniquement)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan-frontend:
    name: Analyse du Frontend (React.js)
    runs-on: self-hosted

    steps:
      # ==================================================
      # 1. Checkout & Setup
      # ==================================================
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: quiz-app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('quiz-app/package-lock.json') }}

      - name: Installer les dépendances frontend
        run: npm install
        working-directory: quiz-app

      - name: Créer le dossier de rapports
        run: mkdir -p quiz-app/reports/{trivy,owasp,gitleaks,semgrep,checkov,kubescape}

      - name: Setup Gitleaks
        run: |
          if [ ! -f gitleaks ]; then
            wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
            tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
            chmod +x gitleaks
          fi

      # ==================================================
      # 2. Build Docker
      # ==================================================
      - name: Build Docker image frontend
        run: docker build -t quiz-app-frontend:latest quiz-app

      # ==================================================
      # 3. Analyses de vulnérabilités (SARIF uniquement)
      # ==================================================

      ## Trivy
      - name: Run Trivy Scan SARIF
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'quiz-app-frontend:latest'
          format: 'sarif'
          output: 'quiz-app/reports/trivy/trivy-report.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Upload Trivy SARIF to Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: quiz-app/reports/trivy/trivy-report.sarif
          category: trivy

      - name: Upload Trivy SARIF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-sarif
          path: quiz-app/reports/trivy/trivy-report.sarif

      ## OWASP Dependency-Check
      - name: Run OWASP Dependency-Check SARIF
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "frontend-quiz-app"
          path: "quiz-app"
          format: "SARIF"
          out: "quiz-app/reports/owasp"
          args: "--enableRetired"
        env:
          JAVA_HOME: /opt/jdk

      - name: Upload OWASP SARIF to Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: quiz-app/reports/owasp/dependency-check-report.sarif
          category: owasp

      - name: Upload OWASP SARIF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: owasp-sarif
          path: quiz-app/reports/owasp/dependency-check-report.sarif

      ## Gitleaks
      - name: Run Gitleaks SARIF
        run: ./gitleaks detect --source="quiz-app" --report-path="quiz-app/reports/gitleaks/gitleaks-report.sarif" --report-format="sarif" --exit-code 0

      - name: Upload Gitleaks SARIF to Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: quiz-app/reports/gitleaks/gitleaks-report.sarif
          category: gitleaks

      - name: Upload Gitleaks SARIF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-sarif
          path: quiz-app/reports/gitleaks/gitleaks-report.sarif

      ## Semgrep
      - name: Run Semgrep SARIF
        run: semgrep scan --config "p/default" --output "quiz-app/reports/semgrep/semgrep-report.sarif" --sarif || true

      - name: Upload Semgrep SARIF to Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: quiz-app/reports/semgrep/semgrep-report.sarif
          category: semgrep

      - name: Upload Semgrep SARIF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sarif
          path: quiz-app/reports/semgrep/semgrep-report.sarif

      # ==================================================
      # 4. Analyse Kubernetes (SARIF uniquement)
      # ==================================================

      ## Installer Checkov
      - name: Installer Checkov
        run: pip install checkov

      ## Checkov SARIF
      - name: Run Checkov SARIF
        run: checkov -d ./kubernetes-manifest -o sarif --output-file-path reports/checkov/checkov-report.sarif
        continue-on-error: true

      - name: Upload Checkov SARIF to Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/checkov/checkov-report.sarif
          category: checkov

      - name: Upload Checkov SARIF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: checkov-sarif
          path: reports/checkov/checkov-report.sarif

      ## Kubescape SARIF
      - name: Run Kubescape SARIF
        uses: kubescape/github-action@main
        with:
          format: 'sarif'
          outputFile: 'reports/kubescape/kubescape-report.sarif'
          scanPath: ./kubernetes-manifest
        continue-on-error: true

      - name: Upload Kubescape SARIF to Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'reports/kubescape/kubescape-report.sarif'
          category: kubescape
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Kubescape SARIF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubescape-sarif
          path: reports/kubescape/kubescape-report.sarif
