name: Analyse de Sécurité MERN (console only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-backend:
    name: 1. Analyse du Backend (Node.js/Express)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances du backend
        run: npm install
        working-directory: ./backend

      - name: Lancer l'analyse OWASP Dependency-Check (console)
        uses: dependency-check/Dependency-Check_Action@1.0.0
        with:
          project: "backend-quiz-app"
          path: "./backend"
          failOnCVSS: 7
