name: Analyse de Sécurité MERN Frontend (avec échec sur vulnérabilité critique)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-frontend:
    name: Analyse du Frontend (React.js)
    runs-on: self-hosted

    steps:
      # --------------------------------------------------
      - name: Nettoyer workspace précédent
        run: |
          echo "Nettoyage du workspace pour éviter les problèmes de permissions..."
          sudo rm -rf $GITHUB_WORKSPACE/*

      # --------------------------------------------------
      - name: Checkout du code
        uses: actions/checkout@v4

      # --------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # --------------------------------------------------
      - name: Installer les dépendances du frontend
        run: npm install
        working-directory: quiz-app

      # --------------------------------------------------
      - name: Créer le dossier de rapports
        run: mkdir -p quiz-app/reports

      # --------------------------------------------------
      - name: Run Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
          chmod +x gitleaks
          ./gitleaks detect \
            --verbose \
            --source="quiz-app" \
            --exit-code 0 \
            --report-format sarif \
            --report-path "quiz-app/reports/gitleaks-report.sarif"

      # --------------------------------------------------
      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config "p/default" \
            --sarif --output "quiz-app/reports/semgrep.sarif" || true

      # --------------------------------------------------
      - name: Lancer l'analyse des dépendances du frontend (OWASP)
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: "frontend-quiz-app"
          path: "quiz-app"
          format: "HTML,SARIF"
          out: "quiz-app/reports"
          args: >
            --enableRetired
        env:
          JAVA_HOME: /opt/jdk

      # --------------------------------------------------
     

      - name: Upload OWASP SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'quiz-app/reports/dependency-check-report.sarif'

