name: Analyse de Sécurité MERN Frontend (avec échec sur vulnérabilité critique)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-frontend:
    name: Analyse du Frontend (React.js)
    runs-on: self-hosted

    steps:
      # --------------------------------------------------
      - name: Nettoyer workspace précédent
        run: |
          echo "Nettoyage du workspace pour éviter les problèmes de permissions..."
          sudo rm -rf $GITHUB_WORKSPACE/*

      # --------------------------------------------------
      - name: Checkout du code
        uses: actions/checkout@v4

      # --------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # --------------------------------------------------
      - name: Installer les dépendances du frontend
        run: npm install
        working-directory: quiz-app

      # --------------------------------------------------
      - name: Créer le dossier de rapports
        run: mkdir -p quiz-app/reports

      # --------------------------------------------------
      - name: Run Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
          chmod +x gitleaks
          ./gitleaks detect \
            --verbose \
            --source="quiz-app" \
            --exit-code 0 \
            --report-format sarif \
            --report-path "quiz-app/reports/gitleaks-report.sarif"

      # --------------------------------------------------
      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config "p/default" \
            --sarif --output "quiz-app/reports/semgrep.sarif" || true

      # --------------------------------------------------
      - name: Lancer l'analyse des dépendances du frontend (OWASP)
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: "frontend-quiz-app"
          path: "quiz-app"
          format: "HTML"
          out: "quiz-app/reports"
          args: >
            --enableRetired
        env:
          JAVA_HOME: /opt/jdk

      # --------------------------------------------------
      - name: Build Docker image for frontend
        run: docker build -t quiz-app-frontend:latest quiz-app

      # --------------------------------------------------
      - name: Scan Docker image with Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.43.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.43.0_Linux-64bit.deb
          trivy image --format json --output quiz-app/reports/trivy-report.json quiz-app-frontend:latest

      # --------------------------------------------------
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-frontend-report
          path: quiz-app/reports/gitleaks-report.sarif
          if-no-files-found: warn

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-frontend-report
          path: quiz-app/reports/semgrep.sarif
          if-no-files-found: warn

      - name: Upload OWASP report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-frontend-report
          path: quiz-app/reports/dependency-check-report.html
          if-no-files-found: warn

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-frontend-report
          path: quiz-app/reports/trivy-report.json
          if-no-files-found: warn
