name: Analyse de Sécurité MERN (avec échec sur vulnérabilité critique)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-backend:
    name: Analyse du Backend (Node.js/Express)
    runs-on: self-hosted

    steps:
      # --------------------------------------------------
      - name: Nettoyer workspace précédent
        run: |
          echo "Nettoyage du workspace pour éviter les problèmes de permissions..."
          sudo rm -rf /home/nasri/iovision/reactjs-quiz-app/actions-runner/_work/app/app/*

      # --------------------------------------------------
      - name: Checkout du code
        uses: actions/checkout@v4

      # --------------------------------------------------
      - name: Debug - Vérifier arborescence
        run: |
          pwd
          ls -R

      # --------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # --------------------------------------------------
      - name: Installer les dépendances du backend
        run: npm install
        working-directory: ./backend

      # --------------------------------------------------
      - name: Créer dossier reports
        run: mkdir -p ./backend/reports

      # --------------------------------------------------
      - name: Lancer l'analyse des dépendances du backend
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: "backend-quiz-app"
          path: "./backend"
          format: "HTML"
          out: "./backend/reports"
          args: >
            --enableRetired
        env:
          JAVA_HOME: /opt/jdk

      # --------------------------------------------------
      - name: Fix permissions du dossier reports
        run: |
          echo "Correction des permissions pour éviter les erreurs EACCES..."
          sudo chown -R $USER:$USER ./backend/reports
          chmod -R 755 ./backend/reports

      # --------------------------------------------------
      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
          name: Depcheck report
          path: ./backend/reports/dependency-check-report.html
          if-no-files-found: warn
