# Nom du fichier : .github/workflows/professional-ci-pipeline.yml

name: Professional CI Pipeline with SARIF Reporting

on: [push] 
 

jobs:
  security-and-validation:
    name: "Security Validation and Build"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: "1. Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Scans globaux ---
      - name: "2. Scan for Secrets with Gitleaks"
        uses: gitleaks/gitleaks-action@v2

      - name: "3. Scan IaC with Checkov"
        uses: bridgecrewio/checkov-action@v12 # Utiliser une version figée
        with:
          directory: ./quiz-app

      - name: "4. Scan K8s Manifests with Kubescape"
        uses: kubescape/github-action@main
        with:
          format: 'sarif'
          output: 'kubescape-results.sarif'
          complianceThreshold: 0

      - name: "5. Upload Kubescape SARIF"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'kubescape-results.sarif'

      # --- Validation du Frontend ---
      - name: "6. Setup Node.js with Cache"
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./quiz-app/package-lock.json

      - name: "7. Install Dependencies & Run Lint/Tests"
        working-directory: ./quiz-app
        run: |
          npm install
          npm run lint
          npm test

      # --- Scans de sécurité applicative ---
      - name: "8. Run Semgrep (SAST) and Generate SARIF"
        uses: returntocorp/semgrep-action@v1
        with:
          source-root: quiz-app/
          generate-sarif: true

      - name: "9. Upload Semgrep SARIF"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: "10. Run OWASP Dependency-Check (SCA)"
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'quiz-app'
          path: 'quiz-app/'
          format: 'SARIF'
          failOnCVSS: 7

      - name: "11. Upload OWASP-DC SARIF"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'quiz-app/reports/dependency-check-report.sarif'

      # --- Build et Scan de l'image Docker ---
      - name: "12. Build Docker Image"
        working-directory: ./quiz-app
        run: docker build -t frontend-test-build .

      - name: "13. Run Trivy Scan and Generate SARIF"
        uses: aquasecurity/trivy-action@0.20.0 # Utiliser une version figée
        with:
          image-ref: 'frontend-test-build'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
          exit-code: '1'

      - name: "14. Upload Trivy SARIF"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
