name: Analyse de Sécurité MERN Frontend (minimal)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-frontend:
    name: Scan du Frontend avec Trivy
    runs-on: self-hosted

    steps:
      # ==================================================
      # 1. PRÉPARATION
      # ==================================================
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances du frontend
        run: npm install
        working-directory: quiz-app

      - name: Build Docker image
        run: docker build -t quiz-app-frontend:latest quiz-app

      # ==================================================
      # 2. SCAN TRIVY
      # ==================================================
      - name: Trivy Image Scan (SARIF)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'quiz-app-frontend:latest'
          format: 'sarif'
          output: 'trivy-report.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '0'   # échoue si vulnérabilités critiques

      # ==================================================
      # 3. UPLOAD VERS GITHUB SECURITY DASHBOARD
      # ==================================================
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif
