name: CI Pipeline for Self-Hosted Runner

on:
  push:
    branches: [ "main" ]

# Permissions globales requises par les différentes actions
permissions:
  contents: read          # Pour le checkout du code
  security-events: write # Pour uploader les résultats SARIF vers l'onglet Sécurité

jobs:
  # ===================================================================
  # ==                  ÉTAPE 1: TESTS FONCTIONNELS                  ==
  # ===================================================================
  frontend-test:
    name: 1. Frontend - Test & Build
    runs-on: self-hosted # Assigné à votre runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies, lint, and test
        working-directory: ./quiz-app
        run: |
          npm ci
          npm run lint
          npm test
      - name: Build application
        working-directory: ./quiz-app
        run: npm run build

  backend-test:
    name: 1. Backend - Test
    runs-on: self-hosted # Assigné à votre runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies, lint, and test
        working-directory: ./backend
        run: |
          npm ci
          npm run lint
          npm test

  # ===================================================================
  # ==               ÉTAPE 2: SCANS DE SÉCURITÉ DU CODE              ==
  # ===================================================================
  security-scan:
    name: 2. Security - Code & Dependency Scans
    runs-on: self-hosted # Assigné à votre runner
    needs: [frontend-test, backend-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks Manually
        run: |
          # Note: Pour optimiser, Gitleaks peut être pré-installé sur le runner
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
          chmod +x gitleaks
          ./gitleaks detect --verbose --source="." --exit-code 0 --report-format sarif --report-path "gitleaks-report.sarif"

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: true

      - name: Create report directories
        run: mkdir -p backend/reports quiz-app/reports

      - name: Run OWASP DC on Backend
        run: |
          # Le dossier /owasp-data sur la machine du runner sert de cache persistant
          # Assurez-vous que ce dossier existe sur votre runner : sudo mkdir -p /owasp-data && sudo chmod 777 /owasp-data
          docker run --rm \
            -v $(pwd )/backend:/src \
            -v /owasp-data:/usr/share/dependency-check/data \
            owasp/dependency-check --project "Backend" --scan /src --format "HTML" --out /src/reports
        continue-on-error: true

      - name: Run OWASP DC on Frontend
        run: |
          docker run --rm \
            -v $(pwd)/quiz-app:/src \
            -v /owasp-data:/usr/share/dependency-check/data \
            owasp/dependency-check --project "Frontend" --scan /src --format "HTML" --out /src/reports
        continue-on-error: true

      - name: Upload SARIF files to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            gitleaks-report.sarif
            semgrep.sarif
      
      - name: Archive OWASP HTML reports (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-reports
          path: |
            backend/reports/
            quiz-app/reports/

  # ===================================================================
  # ==         ÉTAPE 3: BUILD & SCAN DES IMAGES DOCKER LOCALES       ==
  # ===================================================================
  frontend-image:
    name: 3. Frontend - Build & Scan Image
    runs-on: self-hosted # Assigné à votre runner
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build local Docker image
        id: build-image
        run: |
          docker build -t frontend-image:local -f quiz-app/Dockerfile .
          echo "image_name=frontend-image:local" >> $GITHUB_OUTPUT
      - name: Scan local image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build-image.outputs.image_name }}
          format: 'sarif'
          output: 'trivy-frontend-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
      - name: Upload Trivy SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-frontend-results.sarif'

  backend-image:
    name: 3. Backend - Build & Scan Image
    runs-on: self-hosted # Assigné à votre runner
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build local Docker image
        id: build-image
        run: |
          docker build -t backend-image:local -f backend/Dockerfile .
          echo "image_name=backend-image:local" >> $GITHUB_OUTPUT
      - name: Scan local image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build-image.outputs.image_name }}
          format: 'sarif'
          output: 'trivy-backend-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
      - name: Upload Trivy SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-backend-results.sarif'

  # ===================================================================
  # ==        ÉTAPE 4: SCAN DE L'INFRASTRUCTURE AS CODE (IAC)        ==
  # ===================================================================
  iac-scan:
    name: 4. IaC - Scan Kubernetes & Terraform
    runs-on: self-hosted # Assigné à votre runner
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Scan IaC files with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: all
          output_format: sarif
          output_file_path: checkov-results.sarif
          quiet: true
          soft_fail: true
      - name: Upload Checkov SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'checkov-results.sarif'
