name: Test Kubescape SARIF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan-k8s:
    name: Analyse Kubernetes avec Kubescape
    runs-on: self-hosted

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Créer dossier de rapports
        run: mkdir -p reports/kubescape

      - name: Run Kubescape SARIF
        uses: kubescape/github-action@main
        with:
          format: 'sarif'
          outputFile: 'reports/kubescape/kubescape-report.sarif'
          scanPath: ./kubernetes-manifest
        continue-on-error: true

      - name: Upload Kubescape SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'reports/kubescape/kubescape-report.sarif'
          category: kubescape
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
