# Nom du workflow
name: Analyse de Sécurité MERN (avec échec sur vulnérabilité critique)

# Déclencheurs
on:
  push:
    branches: [ main ]

  workflow_dispatch:

# Jobs à exécuter
jobs:
  # --- JOB POUR LE BACKEND ---
  scan-backend:
    name: 1. Analyse du Backend (Node.js/Express)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances du backend
        run: npm install
        working-directory: ./backend

      - name: Lancer l'analyse des dépendances du backend
        # CORRECTION ICI : Ajout de @v4 à la fin de l'action
        uses: owasp/dependency-check-action@v4
        with:
          args: '--project "backend-quiz-app" --scan ./backend --format HTML --failOnCVSS 7'

      - name: Archiver le rapport du backend (si succès)
        # On vérifie que l'étape précédente n'a pas échoué
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: rapport-securite-backend
          path: reports/dependency-check-report.html

 
