name: Analyse de Sécurité MERN Frontend (pipeline complète)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan-frontend:
    name: Analyse du Frontend (React.js)
    runs-on: self-hosted

    steps:
      # ==================================================
      # 1. Checkout & setup
      # ==================================================
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: quiz-app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('quiz-app/package-lock.json') }}

      - name: Installer les dépendances du frontend
        run: npm install
        working-directory: quiz-app

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Créer le dossier de rapports
        run: mkdir -p quiz-app/reports/{trivy,owasp,gitleaks,semgrep,checkov,kubescape}

      # --- Kubescape JSON + SARIF ---
      - name: Run Kubescape JSON
        uses: kubescape/github-action@main
        with:
          format: 'json'
          outputFile: 'quiz-app/reports/kubescape/kubescape-report.json'
          scanPath: ./kubernetes-manifest
        continue-on-error: true

      - name: Convert Kubescape JSON to SARIF (optional)
        run: python scripts/convert_kubescape_json_to_sarif.py \
          quiz-app/reports/kubescape/kubescape-report.json \
          quiz-app/reports/kubescape/kubescape-report.sarif

      - name: Validate Kubescape SARIF
        run: jq empty quiz-app/reports/kubescape/kubescape-report.sarif || echo "Kubescape SARIF may be invalid"

      - name: Upload Kubescape SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: quiz-app/reports/kubescape/kubescape-report.sarif
          category: kubescape

      - name: Upload Kubescape JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-report-json
          path: quiz-app/reports/kubescape/kubescape-report.json
     
