name: Analyse de Sécurité MERN Frontend (avec échec sur vulnérabilité critique)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-frontend:
    name: Analyse du Frontend (React.js)
    runs-on: self-hosted

    steps:
      # --------------------------------------------------
     
      # --------------------------------------------------
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./kubernetes-manifest
          output_format: json
          output_file_path: quiz-app/reports/checkov-report.json

      # --------------------------------------------------
      # Upload des rapports
     
      - name: Upload Checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-frontend-report
          path: quiz-app/reports/checkov-report.json
          if-no-files-found: warn
