# Nom du workflow
name: 1 - Gitleaks Secret Scan (Strict)

on: [push]

jobs:
  gitleaks-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1 : Récupérer le code avec l'historique complet.
      - name: 1. Checkout Code
        uses: actions/checkout@v4
        # --- C'EST LA LIGNE LA PLUS IMPORTANTE ---
        # Elle force le téléchargement de TOUT l'historique.
        with:
          fetch-depth: 0

      # Étape 2 : Exécuter Gitleaks.
      - name: 2. Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
