# Nom du fichier : .github/workflows/full-validation-tolerant.yml

name: Full Validation Pipeline (Tolerant Mode)

on: [push]

jobs:
  full-validation:
    name: "Full Validation (Frontend, IaC, K8s)"
    runs-on: ubuntu-latest

    steps:
      - name: "1. Checkout Code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "2. Scan for Secrets with Gitleaks"
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: "3. Scan IaC with Checkov"
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          soft_fail: true

      - name: "4. Scan K8s Manifests with Kubescape"
        uses: kubescape/github-action@v0.4.0
        with:
          format: 'pretty'
          # On met un seuil de conformité à 0 pour qu'il ne bloque jamais sur ce critère.
          complianceThreshold: 0
          # On ne spécifie PAS de severityThreshold pour qu'il ne bloque pas dessus.

      # ... (le reste du pipeline reste identique) ...

      - name: "5. Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: "6. Install Dependencies & Run Tests"
        working-directory: ./quiz-app
        run: |
          npm install
          npm run lint
          npm test

      - name: "7. Run Semgrep (SAST)"
        uses: returntocorp/semgrep-action@v1
        with:
          source-root: quiz-app/
          config: p/default

      - name: "8. Run OWASP Dependency-Check (SCA)"
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'quiz-app'
          path: 'quiz-app/'
          format: 'HTML'

      - name: "9. Upload OWASP-DC HTML Report as Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: quiz-app/reports/dependency-check-report.html

      - name: "10. Build Docker Image"
        working-directory: ./quiz-app
        run: docker build -t frontend-test-build .

      - name: "11. Run Trivy Scan"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'frontend-test-build'
          format: 'table'
          exit-code: '0'
