name: Gitleaks Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results
          path: results.sarif
