name: Test Checkov SARIF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  checkov-sarif:
    name: Analyse Checkov SARIF
    runs-on: self-hosted

    steps:
      # 1. Checkout
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2. Créer dossier de rapports
      - name: Créer le dossier de rapports
        run: mkdir -p reports/checkov

      # 3. Installer Checkov
      - name: Installer Checkov
        run: pip install checkov

      # 4. Run Checkov SARIF
      - name: Générer rapport Checkov SARIF
        run: checkov -d ./kubernetes-manifest -o sarif --output-file-path reports/checkov/checkov-report.sarif
        continue-on-error: true

      # 5. Valider le SARIF
      - name: Valider Checkov SARIF
        run: jq empty reports/checkov/checkov-report.sarif || echo "SARIF peut être invalide"

      # 6. Upload SARIF sur GitHub
      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/checkov/checkov-report.sarif
          category: checkov

      # 7. Upload du rapport SARIF en artifact
      - name: Upload Checkov SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report-sarif
          path: reports/checkov/checkov-report.sarif
          if-no-files-found: warn
