# Nom du workflow, décrivant clairement son objectif.
name: Core Security Analysis (Secrets, SAST, SCA)

on: [push]

jobs:
  # Un seul job pour analyser le code source du frontend.
  frontend-code-security:
    name: Frontend Source Code Security
    runs-on: ubuntu-latest
    permissions:
      # Permission pour cloner le code.
      contents: read
      # Permission pour que les outils puissent uploader leurs résultats.
      security-events: write

    steps:
      # Étape 1 : Récupérer le code avec l'historique complet.
      - name: 1. Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Scan de Secrets avec Gitleaks.
      # C'est la vérification la plus rapide et la plus critique.
      - name: 2. Scan for Secrets (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        # On le laisse en mode bloquant. Si un secret est trouvé, la pipeline s'arrête.

      # Étape 3 : Scan de votre code avec Semgrep (SAST).
      - name: 3. Scan Application Code (SAST with Semgrep)
        uses: returntocorp/semgrep-action@v1
        # L'action est assez intelligente pour trouver les fichiers pertinents et uploader les résultats.

      # Étape 4 : Préparation pour le scan de dépendances.
      # OWASP DC a besoin que les dépendances soient installées.
      - name: 4. Install Dependencies for SCA
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        run: npm install
        working-directory: ./quiz-app

      # Étape 5 : Scan des dépendances avec OWASP Dependency-Check (SCA).
      - name: 5. Scan Dependencies (SCA with OWASP DC)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          projectName: 'quiz-app-dependencies'
          scanPath: './quiz-app'
          format: 'SARIF'
          # On peut ajouter des arguments pour affiner le scan si nécessaire.
          # Par exemple, pour exclure les dépendances de développement :
          # args: '--nodeaudit.dependency.type dev'

      # Étape 6 : Uploader les résultats du scan de dépendances.
      # Cette étape est nécessaire car l'action OWASP DC ne le fait pas automatiquement.
      - name: 6. Upload SCA Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/dependency-check-report.sarif
