name: React.js CI

on: [push]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quiz-app
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, lint, test, build
        run: |
          npm ci
          npm run lint
          npm run prettier
          npm test
          npm run build
          
        env:
          CI: true

      - name: SonarCloud Analysis (Frontend)
        uses: SonarSource/sonarqube-scan-action@v5
        env:
        
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: quiz-app
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_FRONTEND }}
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.sources=src/
            -Dsonar.verbose=true
