# .github/workflows/ci-cd.yml
# Renommé pour refléter qu'il gère tout le CI/CD

name: CI - Build, Push and Update All Services

on:
  push:
    branches:
      - main
    # On se déclenche si le backend OU le frontend change
    paths:
      - 'backend/**'
      - 'quiz-app/**'

env:
  AWS_REGION: "us-east-1"
  # Dépôt ECR pour le backend
  ECR_REPOSITORY_BACKEND: "iovision-repo" 
  # Dépôt ECR pour le frontend (assurez-vous qu'il existe)
  ECR_REPOSITORY_FRONTEND: "iovision" 

jobs:
  build-push-and-update:
    name: Build, Push and Update Manifests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      # ===================================================================
      # ÉTAPES COMMUNES
      # ===================================================================
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228578233417:role/oicd 
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ===================================================================
      # ÉTAPES POUR LE BACKEND
      # ===================================================================
      - name: Build, tag, and push BACKEND image
        id: build-backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # On utilise un tag lisible
          IMAGE_TAG: backend-${{ github.sha_short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
          echo "image_uri=$ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # ===================================================================
      # ÉTAPES POUR LE FRONTEND
      # ===================================================================
      - name: Build, tag, and push FRONTEND image
        id: build-frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # On utilise un tag lisible
          IMAGE_TAG: frontend-${{ github.sha_short }}
        run: |
          # On utilise le bon dossier pour le build
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG ./quiz-app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG
          echo "image_uri=$ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # ===================================================================
      # ÉTAPE FINALE : MISE À JOUR DES MANIFESTES
      # ===================================================================
      - name: Update manifests and push to Git
        run: |
          # On configure Git
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@github.com'
          
          # On récupère les URIs des images des étapes précédentes
          BACKEND_IMAGE_URI="${{ steps.build-backend.outputs.image_uri }}"
          FRONTEND_IMAGE_URI="${{ steps.build-frontend.outputs.image_uri }}"
          
          echo "Updating backend.yaml with image: $BACKEND_IMAGE_URI"
          sed -i "s|image: .*|image: $BACKEND_IMAGE_URI|" kubernetes-manifest/backend.yaml
          
          echo "Updating frontend.yaml with image: $FRONTEND_IMAGE_URI"
          sed -i "s|image: .*|image: $FRONTEND_IMAGE_URI|" kubernetes-manifest/frontend.yaml
          
          # On publie les deux manifestes modifiés en un seul commit
          git add kubernetes-manifest/backend.yaml kubernetes-manifest/frontend.yaml
          git commit -m "ci: Update images for backend and frontend to ${{ github.sha_short }}"
          git push
