name: Semgrep

on:
  pull_request: {}       # Scan changed files in pull requests
  workflow_dispatch: {}  # Allow manual triggering
  push:
    branches:
      - "main"           # Scan the main branch on push

jobs:
  semgrep_scan:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep # Docker image with Semgrep pre-installed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform Semgrep Analysis
        run: semgrep scan --config auto ./quiz-app
