name: IaC Security Scan (Checkov)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - uses: actions/checkout@v3
    - name: Run Kubescape scanner
      uses: kubescape/github-action@main
      continue-on-error: true # Important: Permet au workflow de continuer même si des vulnérabilités sont trouvées
      with:
        format: sarif
        outputFile: results.sarif
        files: "./kubernetes-manifest"

    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v3 # Mise à jour vers la v3
      with:
        sarif_file: results.sarif
