name: OWASP Dependency-Check — quiz-app (Marketplace Action)

on:
  push:
    branches: [ main ]
    paths:
      - 'quiz-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'quiz-app/**'

jobs:
  dep-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Si tu utilises actions/setup-java plus haut dans d'autres workflows,
      # l'action indique qu'il faut parfois réinitialiser JAVA_HOME — on le met
      # ici pour éviter l'erreur "JAVA_HOME is not defined correctly".
      - name: Run Dependency-Check (Marketplace Action)
        uses: dependency-check/Dependency-Check_Action@main
        env:
          # valeur recommandée par le README de l'action pour correspondre à l'image
          JAVA_HOME: /opt/jdk
        with:
          project: 'Quiz-App'
          path: 'quiz-app'                     # dossier à analyser
          format: 'ALL'                        # HTML, XML, JSON, etc.
          out: 'dependency-check-report'       # dossier de sortie (relatif au workspace)
          args: >
            --prettyPrint
            --failOnCVSS 7                     # option : échoue le job si CVSS >= 7

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
