name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - "main"

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep Analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto          # Utilise les règles automatiques
          json: true            # Génère un JSON dans la console
        continue-on-error: true

      - name: Save JSON report
        run: echo "${{ steps.semgrep.outputs.stdout }}" > semgrep-results.json

      - name: Upload Semgrep JSON report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-report
          path: semgrep-results.json
