name: Gitleaks Scan

on:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks via Marketplace
        uses: zricethezav/gitleaks-action@v2
