# Nom du workflow
name: 'Analyse de Sécurité avec Kubescape'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  kubescape-scan:
    name: 'Scanner avec Kubescape et Uploader les Alertes'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      # Étape 1: Checkout du code - v4 est correct et existe.
      - name: 'Récupérer le code source'
        uses: actions/checkout@v4

      # Étape 2: Lancer le scan Kubescape.
      # La version stable est bien v3. L'erreur peut venir d'un problème de synchronisation
      # sur votre GitHub Enterprise. On garde v3 car c'est la version correcte.
      - name: 'Lancer le scan Kubescape'
        uses: kubescape/github-action@v3
        with:
          format: 'sarif'
          scanCommand: 'scan framework nsa,mitre --scan-cve ./kubernetes-manifest'
          failOnSeverity: 'none'

      # Étape 3: Uploader le rapport SARIF.
      # CORRECTION : La version stable de cette action est v3, pas v4.
      - name: 'Uploader le rapport SARIF vers GitHub Security'
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: results.sarif
