name: Checkov Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkov scan on Kubernetes manifests
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./kubernetes-manifest
          framework: kubernetes
          quiet: true
