name: Gitleaks Scan

on:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks via Marketplace Action
        uses: zricethezav/gitleaks-action@v2
        with:
          # Dossier à scanner (optionnel, default = repo root)
          # scan-path: ./quiz-app   # décommente si tu veux scanner uniquement quiz-app
          config-path: ""          # config par défaut
          ignore-exit-code: true   # ne pas échouer le job si des secrets sont trouvés
