name: Semgrep Scan with semgrep-action

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}
  push:
    branches:
      - "main"

jobs:
  semgrep:
    name: Run Semgrep Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quiz-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep Analysis
        uses: semgrep/semgrep-action@v1
        with:
          directory: ./quiz-app
          config: p/react,p/javascript
