name: Gitleaks Scan (Marketplace simple)

on:
  pull_request: {}
  push:
    branches:
      - "main"

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Lancer le scan via Marketplace
      - name: Run Gitleaks using Marketplace Action
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source=.
        continue-on-error: true   # Le job continue même si des secrets sont trouvés
