name: IaC Security Scan (Kubescape) # Nom clarifié

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - uses: actions/checkout@v3

    - name: Run Kubescape scanner
      uses: kubescape/github-action@main
      continue-on-error: true
      with:
        format: sarif
        # Spécifiez le nom du fichier sans extension. L'action ajoutera .sarif
        outputFile: results 
        files: "./kubernetes-manifest"

    # Étape de débogage optionnelle mais recommandée
    - name: Check for SARIF file
      run: ls -l results.sarif
      continue-on-error: true

    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        # Assurez-vous que le nom ici correspond bien au fichier généré
        sarif_file: results.sarif
