# .github/workflows/ci-cd.yml

name: CI - Security Scan, Build, Push and Update

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'quiz-app/**'

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY_BACKEND: "iovision-repo" 
  ECR_REPOSITORY_FRONTEND: "quiz-app-repo" 

jobs:
  build-scan-push-and-update:
    name: Build, Scan, Push and Update Manifests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228578233417:role/oicd 
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Define Short SHA
        id: vars
        run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT

      # ===================================================================
      # PIPELINE POUR LE BACKEND
      # ===================================================================
      - name: 1. Build BACKEND image
        id: build-backend
        run: |
          IMAGE_TAG="backend-${{ steps.vars.outputs.sha_short }}"
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG"
          docker build -t $IMAGE_URI ./backend
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: 2. Scan BACKEND image with Trivy
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.build-backend.outputs.image_uri }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: 3. Push BACKEND image to ECR
        run: docker push ${{ steps.build-backend.outputs.image_uri }}

      # ===================================================================
      # PIPELINE POUR LE FRONTEND
      # ===================================================================
      - name: 4. Build FRONTEND image
        id: build-frontend
        run: |
          IMAGE_TAG="frontend-${{ steps.vars.outputs.sha_short }}"
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG"
          docker build -t $IMAGE_URI ./quiz-app
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: 5. Scan FRONTEND image with Trivy
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.build-frontend.outputs.image_uri }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: 6. Push FRONTEND image to ECR
        run: docker push ${{ steps.build-frontend.outputs.image_uri }}

      # ... (étapes de build et push) ...

      - name: Update manifests and push to Git
        if: ${{ success() }}
        run: |
          git config --global user.name 'wissNasri'
          git config --global user.email 'wissemnasri81@gmail.com'
          
          # Extraire le TAG de l'URI complet de l'image
          BACKEND_IMAGE_TAG=$(echo "${{ steps.build-backend.outputs.image_uri }}" | cut -d':' -f2)
          FRONTEND_IMAGE_TAG=$(echo "${{ steps.build-frontend.outputs.image_uri }}" | cut -d':' -f2)
          
          # --- FILET DE SÉCURITÉ ---
          if [ -z "$BACKEND_IMAGE_TAG" ] || [ -z "$FRONTEND_IMAGE_TAG" ]; then
            echo "Error: Image tags are empty. Aborting manifest update."
            exit 1
          fi
          
          # Remplacer le marqueur par le nouveau tag
          sed -i "s|IMAGE_TAG_PLACEHOLDER|$BACKEND_IMAGE_TAG|" kubernetes-manifest/backend.yaml
          sed -i "s|IMAGE_TAG_PLACEHOLDER|$FRONTEND_IMAGE_TAG|" kubernetes-manifest/frontend.yaml
          
          # Vérifier s'il y a des changements et faire le commit
          # Note: git diff --staged ne fonctionnera pas ici, utilisez git diff --quiet
          git add kubernetes-manifest/backend.yaml kubernetes-manifest/frontend.yaml
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: Update images to ${{ steps.vars.outputs.sha_short }}"
            git push
          fi
