name: Gitleaks Scan

on:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest  # Docker image officielle de Gitleaks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks scan
        run: |
          # Scanner le dossier complet du repo
          gitleaks detect --source=. --report-format=json --report-path=gitleaks-report.json

      - name: Save Gitleaks report
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json
