# .github/workflows/backend-ci.yml

name: CI - Build and Push Backend Image

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

env:
  AWS_REGION: "us-east-1"
  # --- CORRECTION IMPORTANTE ---
  # On utilise le nom du dépôt ECR qui existe réellement sur AWS.
  ECR_REPOSITORY_BACKEND: "iovision-repo" 

jobs:
  build-and-push-backend:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # ... (les étapes checkout, configure-aws-credentials, login-ecr ne changent pas) ...
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228578233417:role/oicd
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: actions/aws-actions/amazon-ecr-login@v2

      # L'étape de build utilise maintenant la bonne variable
      - name: Build, tag, and push backend image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG ./backend

          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
          
