name: Kubescape scan (logs only)

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Kubescape (scan manifests, no upload)
        # Remplace `@main` par un tag/sha pour pinner la version en prod si tu veux
        uses: kubescape/github-action@main
        with:
          # scanne uniquement les manifests dans ce dossier (relative à la racine du repo)
          files: "kubernetes-manifest/*.yaml"
          # optionnel : choisis un/des frameworks (ou laisse vide pour utiliser le comportement par défaut)
          frameworks: "nsa,mitre"
          # ne génère pas de SARIF/JSON à uploader – les résultats apparaîtront dans les logs
          format: "text"
