name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - "main"

jobs:
  semgrep_scan:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep  # Docker avec Semgrep préinstallé

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep Analysis
        run: semgrep scan --config auto --json ./src > semgrep-results.json
        continue-on-error: true  # Ne bloque pas le workflow si vulnérabilités trouvées

      - name: Upload Semgrep JSON report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-report
          path: semgrep-results.json
