name: Kubescape Security Scan


on:
  pull_request:
  push:
    branches: [main]

jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - uses: actions/checkout@v3
    
    - uses: kubescape/github-action@main
      id: kubescape
      continue-on-error: true
      with:
        format: sarif
        outputFile: results.sarif
        files: "./kubernetes-manifest"
        verbose: true  # ← Logs détaillés
    
    - name: Upload results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3  # ← Version corrigée
      with:
        sarif_file: results.sarif
