name: MERN Stack CI with OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./quiz-app

    steps:
      # 1️⃣ Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Mise en place de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'quiz-app/package-lock.json'

      # 3️⃣ Installation des dépendances
      - name: Install NPM dependencies
        run: npm install

      # 4️⃣ Analyse avec OWASP Dependency-Check (CORRIGÉ)
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'quiz-app'             # Nom du projet (obligatoire)
          path: './quiz-app'              # Chemin à analyser
          format: 'HTML'
          out: 'reports'
          args: >
            --scan .
            --enableExperimental

      # 5️⃣ Upload du rapport HTML
      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dep-check-report
          path: reports
