name: Kubescape scan (SARIF upload)

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Kubescape (generate SARIF)
        uses: kubescape/github-action@main   # ⚠️ remplace @main par un tag/sha stable en prod
        with:
          files: "kubernetes-manifest/*.yaml"
          format: "sarif"
          outputFile: "kubescape-results.sarif"

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kubescape-results.sarif
