name: Gitleaks Scan via Docker

on:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest  # Docker image officielle de Gitleaks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fix Git ownership issue
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Run Gitleaks scan
        run: |
          gitleaks detect --source=. || true
