name: Gitleaks Scan

on:
  pull_request: {}
  push:
    branches:
      - "main"

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest  # Docker officiel Gitleaks

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Exécuter le scan
      - name: Run Gitleaks scan
        run: gitleaks detect --source=.
        continue-on-error: true   # Ne bloque pas le workflow si des secrets sont détectés
