name: Semgrep Scan

on:
  pull_request: {}          # Déclenche à chaque PR
  workflow_dispatch: {}     # Déclenchement manuel
  push:
    branches:
      - "main"             # Déclenche sur push vers main

jobs:
  semgrep_scan:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep # Docker avec Semgrep pré-installé

    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Exécuter Semgrep pour scanner le code
      - name: Perform Semgrep Analysis
        run: semgrep scan --config auto ./src
