name: OWASP Dependency-Check — quiz-app

on:
  push:
    branches: [ main ]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depcheck_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project with Maven
        run: mvn clean install

      - name: Run Dependency-Check (Marketplace Action)
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'Quiz-App'
          path: 'quiz-app'             # dossier à analyser
          format: 'ALL'                # HTML, XML, JSON
          out: 'dependency-check-report'
          args: >
            --failOnCVSS 7
            --enableRetired
        env:
          JAVA_HOME: /opt/jdk          # nécessaire pour éviter l'erreur JAVA_HOME

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/dependency-check-report
