name: OWASP Dependency-Check — quiz-app (minimal)

on:
  push:
    branches: [ main ]
    paths:
      - 'quiz-app/**'

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Dependency-Check on quiz-app
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Quiz-App'
          path: 'quiz-app'
          format: 'ALL'
          out: 'dependency-check-report'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: Depcheck report
          path: dependency-check-report
