name: Semgrep Scan (Marketplace)

on:
  pull_request: {}
  push:
    branches:
      - "main"

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Lancer Semgrep via Marketplace
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
        continue-on-error: true  # Le workflow continue même si des vulnérabilités sont trouvées
