name: Semgrep

on:
  pull_request: {}      # Scan des fichiers modifiés dans les PR
  workflow_dispatch: {} # Lancement manuel possible
  push:
    branches:
      - "main"          # Scan du code mergé sur main

jobs:
  semgrep_scan:
    name: Semgrep Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep Analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto   # Utilisation automatique des règles adaptées
