name: Semgrep Scan (Docker Image)

on:
  pull_request: {}
  push:
    branches:
      - "master"

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep  # Docker image avec Semgrep préinstallé

    steps:
      # Étape 1 : Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Lancer Semgrep
      - name: Run Semgrep scan
        run: semgrep scan -q --config auto ./
        continue-on-error: true  # Ne bloque pas le workflow si des vulnérabilités sont trouvées
