name: Semgrep Frontend Scan

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - "main"

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Exécuter Semgrep via args
      - name: Semgrep Scan JSON
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          args: --json --output semgrep-report.json ./quiz-app/src


