name: Gitleaks Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          # Ligne ajoutée pour être explicite : scanner tout le projet
          source: ${{ github.workspace }}
          
          # Vos configurations existantes
          report_format: json
          report_path: ${{ github.workspace }}/gitleaks-report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Gitleaks report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: ${{ github.workspace }}/gitleaks-report.json
