# .github/workflows/ci-cd.yml

name: CI - Build, Push and Update All Services

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'quiz-app/**'

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY_BACKEND: "iovision-repo" 
  ECR_REPOSITORY_FRONTEND: "quiz-app-repo" 

jobs:
  build-push-and-update:
    name: Build, Push and Update Manifests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228578233417:role/oicd 
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- AMÉLIORATION : Définir le hash court de manière fiable ---
      - name: Define Short SHA
        id: vars
        run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT

      # --- BACKEND ---
      - name: Build, tag, and push BACKEND image
        id: build-backend
        run: |
          # On utilise la variable de sortie de l'étape précédente
          IMAGE_TAG="backend-${{ steps.vars.outputs.sha_short }}"
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG
          echo "image_uri=$ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # --- FRONTEND ---
      - name: Build, tag, and push FRONTEND image
        id: build-frontend
        run: |
          # On utilise la même variable fiable
          IMAGE_TAG="frontend-${{ steps.vars.outputs.sha_short }}"
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG ./quiz-app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG
          echo "image_uri=$ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # --- MISE À JOUR DES MANIFESTES ---
      - name: Update manifests and push to Git
        if: ${{ success() }}
        run: |
          git config --global user.name 'wissNasri'
          git config --global user.email 'wissemnasri81@gmail.com'
          
          BACKEND_IMAGE_URI="${{ steps.build-backend.outputs.image_uri }}"
          FRONTEND_IMAGE_URI="${{ steps.build-frontend.outputs.image_uri }}"
          
          if [ -z "$BACKEND_IMAGE_URI" ] || [ -z "$FRONTEND_IMAGE_URI" ]; then
            echo "Error: Image URIs are empty. Aborting."
            exit 1
          fi
          
          sed -i "s|image: .*|image: $BACKEND_IMAGE_URI|" kubernetes-manifest/backend.yaml
          sed -i "s|image: .*|image: $FRONTEND_IMAGE_URI|" kubernetes-manifest/frontend.yaml
          
          # On ne commite que s'il y a des changements
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git add kubernetes-manifest/backend.yaml kubernetes-manifest/frontend.yaml
            git commit -m "ci: Update images to ${{ steps.vars.outputs.sha_short }}"
            git push
          fi
