# Nom du workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Gitleaks Scan

# Déclencheurs du workflow
on:
  push:
    branches:
      - main # ou votre branche principale (ex: master)
  pull_request:
    branches:
      - main # ou votre branche principale

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v4


      # Étape 2: Exécuter l'action Gitleaks
      - name: Run Gitleaks Action
        uses: gitleaks/gitleaks-action@v2
        env:
          # Variable spéciale pour passer des arguments directement à la commande gitleaks
          # On lui demande de générer un rapport JSON nommé 'gitleaks-report.json'
          GITLEAKS_ARGS: '--report-path=gitleaks-report.json --report-format=json'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # La pipeline continue même si des fuites sont trouvées

      # Étape 3: Uploader le rapport Gitleaks en tant qu'artefact
      - name: Upload Gitleaks JSON report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report-json # Nom de l'artefact
          path: gitleaks-report.json # Chemin vers le fichier à uploader
          retention-days: 5 # Optionnel: combien de temps garder l'artefact

