name: Semgrep

on:
  pull_request: {}      
  workflow_dispatch: {} 
  push:
    branches:
      - "main"

jobs:
  semgrep_scan:
    name: Semgrep Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: pip install semgrep

      - name: Perform Semgrep Analysis and generate JSON report
        run: semgrep --config auto --json ./ > semgrep-results.json
        continue-on-error: true  # Ne bloque pas le workflow si vulnérabilités trouvées

      - name: Upload Semgrep JSON report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-report
          path: semgrep-results.json
