name: React.js CI + Semgrep (Final Corrected)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'quiz-app/**'
      - 'kubernetes-manifest/**'

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY_BACKEND: "iovision-repo"
  ECR_REPOSITORY_FRONTEND: "quiz-app-repo"
  ECR_REPOSITORY_POPULATE: "populate-repo"

jobs:
  # ===================================================================
  # JOB 1: DÉTECTER LES FICHIERS MODIFIÉS
  # ===================================================================
  check-changes:
    name: Check for file changes
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.changed-files.outputs.backend_changed }}
      frontend_changed: ${{ steps.changed-files.outputs.frontend_changed }}
      manifests_changed: ${{ steps.changed-files.outputs.manifests_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            backend_changed:
              - 'backend/**'
            frontend_changed:
              - 'quiz-app/**'
            manifests_changed:
              - 'kubernetes-manifest/**'

  # ===================================================================
  # PISTE FRONTEND : TOUS LES JOBS S'EXÉCUTENT EN PARALLÈLE
  # ===================================================================
  frontend-test:
    needs: check-changes
    if: needs.check-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quiz-app
    strategy:
      matrix:
        node-version: [20.x]
        architecture: [x64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, Lint, Test
        run: |
          npm i
          npm run lint
          npm install --save-dev --save-exact prettier
          npm run prettier
          npm test
        env:
          CI: true 
      - name: Build
        run: npm run build

  semgrep-scan-frontend:
    needs: check-changes
    if: needs.check-changes.outputs.frontend_changed == 'true'
    name: Semgrep Analysis (quiz-app)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    defaults:
      run:
        working-directory: ./quiz-app
    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config auto . --json --output semgrep-report-frontend.json
      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-frontend-report
          path: ./quiz-app/semgrep-report-frontend.json

  gitleaks-scan-frontend:
    needs: check-changes
    if: needs.check-changes.outputs.frontend_changed == 'true'
    name: Gitleaks Analysis (quiz-app)
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest
    defaults:
      run:
        working-directory: ./quiz-app
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: gitleaks detect --source . --no-git --verbose --report-format json --report-path gitleaks-report-frontend.json
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: gitleaks-json-frontend-report
          path: ./quiz-app/gitleaks-report-frontend.json
    
  dependency-check-frontend:
    needs: check-changes
    if: needs.check-changes.outputs.frontend_changed == 'true'
    name: OWASP Dependency-Check (quiz-app)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'quiz-app/package-lock.json'
      - run: npm install
        working-directory: ./quiz-app
      - uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'quiz-app-frontend'
          path: './quiz-app'
          format: 'HTML'
          out: 'reports-frontend'
          args: >
            --scan .
            --enableExperimental
      - uses: actions/upload-artifact@v4
        with:
          name: owasp-dep-check-frontend-report
          path: reports-frontend
        
  # ===================================================================
  # PISTE BACKEND : TOUS LES JOBS S'EXÉCUTENT EN PARALLÈLE
  # ===================================================================
  backend-test:
    needs: check-changes
    if: needs.check-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      matrix:
        node-version: [20.x]
        architecture: [x64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, Lint, Test
        run: |
          npm i
          npm run lint
          npm install --save-dev --save-exact prettier
          npm run prettier
          npm test
        env:
          CI: true 

  semgrep-scan-backend:
    needs: check-changes
    if: needs.check-changes.outputs.backend_changed == 'true'
    name: Semgrep Analysis (backend)
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config auto . --json --output semgrep-report-backend.json
      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-backend-report
          path: ./backend/semgrep-report-backend.json

  gitleaks-scan-backend:
    needs: check-changes
    if: needs.check-changes.outputs.backend_changed == 'true'
    name: Gitleaks Analysis (backend)
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: gitleaks detect --source . --no-git --verbose --report-format json --report-path gitleaks-report-backend.json
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: gitleaks-json-backend-report
          path: ./backend/gitleaks-report-backend.json
  
  dependency-check-backend:
    needs: check-changes
    if: needs.check-changes.outputs.backend_changed == 'true'
    name: OWASP Dependency-Check (backend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
      - run: npm install
        working-directory: ./backend
      - uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'quiz-app-backend'
          path: './backend'
          format: 'HTML'
          out: 'reports-backend'
          args: >
            --scan .
            --enableExperimental
      - uses: actions/upload-artifact@v4
        with:
          name: owasp-dep-check-backend-report
          path: reports-backend

  # ===================================================================
  # JOBS DE BUILD (ATTENDENT LA FIN DE LEUR PISTE RESPECTIVE)
  # ===================================================================
  build-backend:
    name: "Build & Push: Backend"
    needs: [backend-test, semgrep-scan-backend, gitleaks-scan-backend, dependency-check-backend]
    if: always() && needs.backend-test.result != 'skipped'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      image_tag_backend: ${{ steps.vars-backend.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228578233417:role/oicd
          aws-region: ${{ env.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Define Backend Image Tag
        id: vars-backend
        run: echo "image_tag=backend-$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Build and Push Backend Image
        id: build-image-backend
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:${{ steps.vars-backend.outputs.image_tag }}"
          docker build -t $IMAGE_URI ./backend
          docker push $IMAGE_URI
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
      - name: Scan BACKEND image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.build-image-backend.outputs.image_uri }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  build-populate:
    name: "Build & Push: Populate"
    needs: [backend-test, semgrep-scan-backend, gitleaks-scan-backend, dependency-check-backend]
    if: always() && needs.backend-test.result != 'skipped'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      image_tag_populate: ${{ steps.vars-populate.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228578233417:role/oicd
          aws-region: ${{ env.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Define Populate Image Tag
        id: vars-populate
        run: echo "image_tag=populate-$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Build and Push Populate Image
        id: build-image-populate
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY_POPULATE:${{ steps.vars-populate.outputs.image_tag }}"
          docker build -t $IMAGE_URI -f ./backend/Dockerfile.populate ./backend
          docker push $IMAGE_URI
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
      - name: Scan POPULATE image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.build-image-populate.outputs.image_uri }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  build-frontend: 
    name: "Build & Push: Frontend"
    needs: [frontend-test, semgrep-scan-frontend, gitleaks-scan-frontend, dependency-check-frontend]
    if: always() && needs.frontend-test.result != 'skipped'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228578233417:role/oicd
          aws-region: ${{ env.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Define Frontend Image Tag
        id: vars
        run: echo "image_tag=frontend-$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Build and Push Frontend Image
        id: build-image
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:${{ steps.vars.outputs.image_tag }}"
          docker build -t $IMAGE_URI ./quiz-app
          docker push $IMAGE_URI
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
      - name: Scan FRONTEND image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.build-image.outputs.image_uri }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  # ===================================================================
  # JOB DE SYNCHRONISATION ET DE DÉPLOIEMENT
  # ===================================================================
  update-manifests:
    name: "Deploy: Update Manifests for ArgoCD"
    runs-on: ubuntu-latest
    needs: [check-changes, build-backend, build-frontend, build-populate]
    if: always() && (needs.build-backend.result == 'success' || needs.build-frontend.result == 'success' || needs.build-populate.result == 'success' || needs.check-changes.outputs.manifests_changed == 'true')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update manifests and push to Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          BACKEND_TAG=${{ needs.build-backend.outputs.image_tag_backend }}
          POPULATE_TAG=${{ needs.build-populate.outputs.image_tag_populate }}
          FRONTEND_TAG=${{ needs.build-frontend.outputs.image_tag }}
          
          if [[ -n "$BACKEND_TAG" ]]; then
            sed -i "s|\(image: .*iovision-repo:\).*|\1$BACKEND_TAG|" kubernetes-manifest/backend.yaml
          fi
          if [[ -n "$POPULATE_TAG" ]]; then
            sed -i "s|\(image: .*populate-repo:\).*|\1$POPULATE_TAG|" kubernetes-manifest/populate-job.yaml
          fi
          if [[ -n "$FRONTEND_TAG" ]]; then
            sed -i "s|\(image: .*quiz-app-repo:\).*|\1$FRONTEND_TAG|" kubernetes-manifest/frontend.yaml
          fi
          
          git add kubernetes-manifest/*.yaml
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci(deploy): Update image tags to $(echo ${{ github.sha }} | cut -c1-8)"
            git push
          fi

  # ===================================================================
  # JOBS D'ANALYSE POST-DÉPLOIEMENT
  # ===================================================================
  k8s-manifest-scan:
    needs: update-manifests
    if: always() && needs.update-manifests.result == 'success'
    name: K8s Manifests Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@master   
        with:
          directory: ./kubernetes-manifest
          framework: kubernetes
          output_format: json
          output_file_path: ./checkov-report.json
          quiet: true
          continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: ./checkov-report.json
      - uses: kubescape/github-action@main   
        with:
          files: "kubernetes-manifest/*.yaml"
          format: json
          outputFile: ./kubescape-report.json
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: kubescape-report
          path: ./kubescape-report.json

  gitleaks-scan-manifests:
    needs: update-manifests
    if: always() && needs.update-manifests.result == 'success'
    name: Gitleaks Analysis (kubernetes-manifest)
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest
    defaults:
      run:
        working-directory: ./kubernetes-manifest
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: gitleaks detect --source . --no-git --verbose --report-format json --report-path gitleaks-report-manifests.json
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: gitleaks-json-manifests-report
          path: ./kubernetes-manifest/gitleaks-report-manifests.json
