name: DAST Scan avec Docker Compose et ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    name: Lancer, Exposer avec ngrok et Scanner l'application

    steps:
      - name: 1. Cloner le code du projet
        uses: actions/checkout@v4

      - name: 2. Construire et lancer les services avec Docker Compose
        run: |
          echo "Construction des images et démarrage des conteneurs en arrière-plan..."
          docker-compose -f app/docker-compose.yml up --build -d

      - name: 3. Attendre que l'application soit prête
        run: |
          echo "Attente du démarrage du service frontend sur le port 8080..."
          timeout 120s bash -c 'until curl -s http://localhost:8080 > /dev/null; do echo "En attente du frontend..."; sleep 5; done'
          echo "Le frontend est prêt !"

      # --- NOUVELLES ÉTAPES POUR NGROK ---
      - name: 4. Exposer l'application avec ngrok
        uses: ngrok/ngrok-github-action@v1
        with:
          # Utilise le secret que vous venez de configurer dans GitHub
          authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          # Expose le port 8080 (celui du frontend )
          port: 8080
          # Stocke l'URL générée dans un fichier pour l'afficher plus tard
          log: "ngrok.log"

      - name: 5. Afficher l'URL publique ngrok
        run: |
          echo "################################################"
          echo "## L'application est accessible publiquement à l'adresse suivante :"
          cat ngrok.log
          echo "################################################"
          
      # --- FIN DES NOUVELLES ÉTAPES ---

      - name: 6. Lancer le scan de sécurité DAST (OWASP ZAP)
        uses: zaproxy/action-baseline@v0.11.0
        with:
          # ZAP peut maintenant utiliser soit localhost, soit l'URL ngrok.
          # Utilisons localhost car c'est plus direct et rapide pour le scan.
          target: 'http://localhost:8080'
          
      - name: 7. Arrêter les services Docker Compose
        if: always( )
        run: |
          echo "Arrêt des conteneurs..."
          docker-compose -f app/docker-compose.yml down
