name: DAST Scan avec Nginx Reverse Proxy (Débogage Final)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    name: Lancer, Exposer avec Nginx/ngrok et Scanner

    steps:
      - name: 1. Cloner le code du projet
        uses: actions/checkout@v4

      - name: 2. Construire et lancer les services avec Docker Compose
        run: |
          echo "Construction des images et démarrage de la pile applicative..."
          docker compose up --build -d

      - name: 3. Attendre que Nginx soit prêt
        run: |
          echo "Attente du démarrage du reverse proxy Nginx sur le port 80..."
          if ! timeout 60s bash -c 'until curl -sf http://localhost:80 > /dev/null; do echo "En attente de Nginx..."; sleep 5; done'; then
            echo "ERREUR: Nginx n'a pas démarré à temps. Affichage des logs..."
            docker compose logs
            exit 1
          fi
          echo "Nginx est prêt !"

      # --- ÉTAPE DE DÉBOGAGE DÉCISIVE ---
      - name: 3.5. Tester la route API directement avec cURL
        run: |
          echo "############################################################"
          echo "## TEST DIRECT DE LA ROUTE /api/questions VIA NGINX ##"
          echo "############################################################"
          # La commande -v (verbeux ) nous montrera les en-têtes de la requête et de la réponse.
          # On saura exactement ce que Nginx nous renvoie.
          curl -v http://localhost:80/api/questions
          echo "############################################################"
          echo "## FIN DU TEST DIRECT ##"
          echo "############################################################"

      # ... reste du pipeline inchangé ...
      - name: 4. Installer et lancer ngrok
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz | sudo tar xvz -C /usr/local/bin
          ngrok config add-authtoken $NGROK_AUTHTOKEN
          ngrok http 80 --log=stdout > ngrok.log &
          sleep 5

      - name: 5. Afficher l'URL publique et la définir pour le scan
        id: scan
        run: |
          PUBLIC_URL=$(grep -o 'url=https://[0-9a-zA-Z.-]*\.ngrok-free\.app' ngrok.log | cut -d'=' -f2 )
          echo "## L'application est accessible à l'adresse suivante : $PUBLIC_URL"
          echo "public_url=$PUBLIC_URL" >> $GITHUB_OUTPUT

      - name: 6. Lancer le scan de sécurité DAST (OWASP ZAP)
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: ${{ steps.scan.outputs.public_url }}
          
      - name: 7. Arrêter tous les services
        if: always()
        run: |
          echo "Arrêt des conteneurs Docker..."
          docker compose down
          echo "Arrêt de l'agent ngrok..."
          pkill ngrok || true
