name: "Analyse DAST Approfondie (Full Scan)"

on:
  workflow_dispatch:
    inputs:
      backend_image_tag:
        description: 'Tag de l''image backend (ex: backend-de6efe22)'
        required: true
        default: 'backend-de6efe22'
      frontend_image_tag:
        description: 'Tag de l''image frontend (ex: frontend-de6efe22)'
        required: true
        default: 'frontend-de6efe22'

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY_BACKEND: "iovision-repo"
  ECR_REPOSITORY_FRONTEND: "quiz-app-repo"

jobs:
  run-full-dast-analysis:
    name: "Lancer le Scan DAST Approfondi"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout du code"
        uses: actions/checkout@v4

      - name: "Connexion à AWS ECR"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Démarrer l'environnement de test avec Docker Compose"
        env:
          BACKEND_IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.event.inputs.backend_image_tag }}
          FRONTEND_IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_FRONTEND }}:${{ github.event.inputs.frontend_image_tag }}
        run: |
          echo "Démarrage de l'environnement..."
          docker compose -f docker-compose.dast.yml up -d

      - name: "Attendre que l'application soit prête"
        run: |
          echo "Attente de la disponibilité du frontend sur http://localhost:8080..."
          timeout 120s bash -c 'until curl -s --head --fail http://localhost:8080 > /dev/null; do echo "En attente..."; sleep 5; done'
          echo "Application prête !"

      # --- ÉTAPE CLÉ : LE FULL SCAN ---
      - name: "Lancer le Scan DAST Approfondi (Full Scan )"
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          # Cible du scan : l'application tourne sur le runner, accessible via localhost.
          target: "http://localhost:8080/"
          
          # Le "spider" explore le site pendant 2 minutes pour découvrir les pages.
          spider_minutes: 2
          
          # Le pipeline n'échouera que pour les alertes critiques de niveau "High".
          fail_on_risk: 'High'

      - name: "Arrêter l'environnement de test"
        if: always( )
        run: |
          echo "Affichage des logs des conteneurs avant l'arrêt..."
          docker compose -f docker-compose.dast.yml logs
          echo "Arrêt de l'environnement Docker Compose..."
          docker compose -f docker-compose.dast.yml down
