# Fichier pour lancer l'environnement de test DAST
version: '3.8'

services:
  backend:
    image: ${BACKEND_IMAGE_URI}
    container_name: dast-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/quizdb
    depends_on:
      - mongo
    networks:
      - dast-network

  frontend:
    image: ${FRONTEND_IMAGE_URI}
    container_name: dast-frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_REACT_APP_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - dast-network

  mongo:
    image: mongo:4.4.6
    container_name: dast-mongo
    networks:
      - dast-network

networks:
  dast-network:
