name: "Analyse de Sécurité DAST à la Demande"

on:
  workflow_dispatch:
    inputs:
      backend_image_tag:
        description: 'Tag de l''image backend (ex: backend-de6efe22)'
        required: true
        # J'ai mis à jour la valeur par défaut avec un tag réel de votre ECR
        default: 'backend-de6efe22'
      frontend_image_tag:
        description: 'Tag de l''image frontend (ex: frontend-de6efe22)'
        required: true
        # J'ai mis à jour la valeur par défaut avec un tag réel de votre ECR
        default: 'frontend-de6efe22'

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY_BACKEND: "iovision-repo"
  ECR_REPOSITORY_FRONTEND: "quiz-app-repo"

jobs:
  run-dast-analysis:
    name: "Lancer le Scan DAST"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout du code"
        uses: actions/checkout@v4

      - name: "Connexion à AWS ECR"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228578233417:role/oicd
          aws-region: ${{ env.AWS_REGION }}
      - name: "Login to Amazon ECR"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: "Démarrer l'environnement de test"
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          BACKEND_IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.event.inputs.backend_image_tag }}
          FRONTEND_IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_FRONTEND }}:${{ github.event.inputs.frontend_image_tag }}
        run: |
          echo "Utilisation de l'image backend: $BACKEND_IMAGE_URI"
          echo "Utilisation de l'image frontend: $FRONTEND_IMAGE_URI"
          
          # --- MODIFICATION ICI ---
          # Remplacement de "docker-compose" par "docker compose" (avec un espace)
          docker compose -f docker-compose.dast.yml up -d

      - name: "Attendre que l'application soit prête"
        run: |
          echo "Attente de la disponibilité du frontend sur http://localhost:8080..."
          timeout 120s bash -c 'until curl -s --head --fail http://localhost:8080 > /dev/null; do echo "En attente..."; sleep 5; done'
          echo "Application prête pour le scan !"

      - name: "Lancer le scan DAST avec OWASP ZAP"
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "http://localhost:8080/"
          fail_action: true
          artifact_name: "zap-dast-report"

      - name: "Arrêter l'environnement de test"
        if: always( )
        run: |
          echo "Affichage des logs des conteneurs avant l'arrêt..."
          # --- MODIFICATION ICI ---
          # Remplacement de "docker-compose" par "docker compose" (avec un espace)
          docker compose -f docker-compose.dast.yml logs
          
          echo "Arrêt de l'environnement Docker Compose..."
          docker compose -f docker-compose.dast.yml down
