name: "Manual Deploy: Promote to Production"

on:
  workflow_dispatch:
    inputs:
      commit_sha_tag:
        description: 'Le tag de la version à déployer (ex: a1b2c3d4)'
        required: true
        type: string
      confirm_production_deploy:
        description: 'Tapez "deploy-to-prod" pour confirmer.'
        required: true
        type: string

jobs:
  promote-to-production:
    name: "Promote to Production"
    if: github.event.inputs.confirm_production_deploy == 'deploy-to-prod'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Update Production Manifests"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          TAG=${{ github.event.inputs.commit_sha_tag }}
          
          sed -i "s|\(image: .*iovision-repo:\).*|\1backend-${TAG}|" kubernetes-manifest/backend.yaml
          sed -i "s|\(image: .*quiz-app-repo:\).*|\1frontend-${TAG}|" kubernetes-manifest/frontend.yaml
          sed -i "s|\(image: .*populate-repo:\).*|\1populate-${TAG}|" kubernetes-manifest/populate-job.yaml
      - name: "Commit and Push Production Manifests"
        run: |
          git add kubernetes-manifest/backend.yaml kubernetes-manifest/frontend.yaml kubernetes-manifest/populate-job.yaml
          if git diff --cached --quiet; then
            echo "No changes detected. The requested tag might already be deployed."
          else
            git commit -m "chore(prod): Promote image tag '${{ github.event.inputs.commit_sha_tag }}' to production"
            git push
          fi
